### ISSUE TITLE
[EngAut] RFCs Referenda status tracker / notifications

### ISSUE THREAD

**Issue by mordamax** [paritytech/eng-automation#2]
Background https://github.com/polkadot-fellows/RFCs/issues/57

**Goal**
To increase the interaction and/or awareness in the context of RFC PR for the ongoing referendum status

**Desired outcome**:
Author and commenters of RFC PR are notified about the _Submitted_ or _Confirmed_ [rejected/approved] status changes of Referendum related to this PR 

**Solution**
implement a periodical tracker, which can scan subsquare collectives referendums, store the statues and map them to existing PRs in polkadot-fellows/RFCs

- when new referendum (related to this PR) is submitted - post a link to subsquare as a new comment (status Submitted)
- when the existing referendum (prelated to this PR) changed in its status - post a status change and link as new comment. (Post only if status changed to Confirmed with the according outcome - approved/rejected)
```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/rfc-action/pull/28
- [ ] https://github.com/polkadot-fellows/RFCs/pull/68
- [ ] https://github.com/paritytech/eng-automation/issues/4
```

**Comment by rzadp** [comment]
As a bonus, we will be able to automatically trigger `rfc-action` in order to close/merge PRs.

**Comment by mordamax** [comment]
> As a bonus, we will be able to automatically trigger `rfc-action` in order to close/merge PRs.

great idea! I'd plan though after few successful (or not 🥲) runs to make sure it identifies correctly etc ))

**Comment by mordamax** [comment]
Last week @Bullrich added new cron job which tracks only newly posted proposals https://github.com/paritytech/rfc-action/pull/28. The other statuses will be implemented lated in https://github.com/paritytech/eng-automation/issues/4

**Comment by Bullrich** [comment]
First part of the task has been completed:

RFC-Action has been updated to contain a cron job, and this cron job tracks ongoing referendas and post them in open PRs if it is related.

## Related issues
- polkadot-fellows/RFCs#57
  - https://github.com/paritytech/rfc-action/pull/28
  - polkadot-fellows/RFCs#68
    - polkadot-fellows/RFCs#69

**Comment by mordamax** [comment]
weekly update: no updates this week

**Comment by Bullrich** [comment]
Added PR to track completed referendas:
- https://github.com/paritytech/rfc-action/pull/34

**Comment by Bullrich** [comment]
Created PR to merge paritytech/rfc-action#34 into RFCs repository:
- https://github.com/polkadot-fellows/RFCs/pull/80

**Comment by Bullrich** [comment]
Created new PR to update the correct action (I updated the wrong action):
- https://github.com/polkadot-fellows/RFCs/pull/83

**Comment by mordamax** [comment]
![image](https://github.com/paritytech/eng-automation/assets/1177472/e841e6ea-9281-4671-b5a8-febe313185b1)

🚀 

Thanks @Bullrich!
