### ISSUE TITLE
[EngAut] Polkadot Fellowship Automation - Q2 2024

### ISSUE THREAD

**Issue by mordamax** [paritytech/eng-automation#8]
```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/review-bot/issues/118
- [ ] https://github.com/paritytech/review-bot/issues/92
- [ ] https://github.com/paritytech/up-to-date-action/issues/14
- [ ] https://github.com/polkadot-fellows/runtimes/pull/76
- [ ] https://github.com/polkadot-fellows/runtimes/pull/192
- [ ] https://github.com/polkadot-fellows/runtimes/issues/372
- [ ] https://github.com/polkadot-fellows/xcm-format/issues/62
- [ ] https://github.com/paritytech/review-bot/issues/122
- [ ] https://github.com/paritytech/infrastructure/issues/41
```

**Comment by Bullrich** [comment]
Currently blocked in polkadot-fellows/runtimes#192.

Waiting for reply from the fellowship.

---

We are checking if https://github.com/paritytech/review-bot/issues/92 can be closed as the runtimes have separated the current situation.

---

https://github.com/paritytech/up-to-date-action/issues/14 is waiting for https://github.com/polkadot-fellows/runtimes/pull/272 to be merged

**Comment by Bullrich** [comment]
I finally managed to properly solve the problem in:
- https://github.com/polkadot-fellows/runtimes/pull/76

Now I'm waiting for new reviews as I have drastically changed the code.

I implemented the solutions from:
- paritytech/polkadot-sdk#4152
- paritytech/polkadot-sdk#3431

**Comment by Bullrich** [comment]
Waiting for the following PRs to be reviewed/merged:
- https://github.com/polkadot-fellows/runtimes/pull/272
- https://github.com/polkadot-fellows/runtimes/pull/192
- https://github.com/polkadot-fellows/runtimes/pull/76

**Comment by Bullrich** [comment]
> Waiting for the following PRs to be reviewed/merged:
> 
> * [up-to-date action can be activated by auto-merge-bot polkadot-fellows/runtimes#272](https://github.com/polkadot-fellows/runtimes/pull/272)
> * [Unified tests into final step ✅  polkadot-fellows/runtimes#192](https://github.com/polkadot-fellows/runtimes/pull/192)
> * [added script to dismiss reviews polkadot-fellows/runtimes#76](https://github.com/polkadot-fellows/runtimes/pull/76)

Still waiting for this PRs to be reviewed.

**Comment by Bullrich** [comment]
Merged the following PRs 
- polkadot-fellows/runtimes#272
- polkadot-fellows/runtimes#76

Resolved the following tickets:
- https://github.com/paritytech/up-to-date-action/issues/14
- https://github.com/paritytech/auto-merge-bot/issues/23
- https://github.com/polkadot-fellows/runtimes/issues/60

**Comment by Bullrich** [comment]
A bug was reported for an individual case.

No new updates.

**Comment by Bullrich** [comment]
https://github.com/polkadot-fellows/xcm-format/issues/65 was created as a requirement for https://github.com/polkadot-fellows/xcm-format/issues/62#issuecomment-2161233184

**Comment by Bullrich** [comment]
Done the following tasks:
- https://github.com/polkadot-fellows/xcm-format/issues/62
  - https://github.com/polkadot-fellows/xcm-format/issues/67
  - Completed https://github.com/polkadot-fellows/xcm-format/issues/68
  - https://github.com/polkadot-fellows/xcm-format/issues/65
  - Completed with https://github.com/polkadot-fellows/xcm-format/issues/66

**Comment by Bullrich** [comment]
Added new task:
- https://github.com/polkadot-fellows/runtimes/issues/372

**Comment by Bullrich** [comment]
Added https://github.com/paritytech/review-bot/issues/122 as a task

**Comment by mordamax** [comment]
Opened a PR for Weights generation https://github.com/polkadot-fellows/runtimes/pull/406
There's no SH runner for now, but it won't fail using ubuntu-22.04, so when runner is ready it could be easily replaced then

**Comment by mutantcornholio** [comment]
Released and deployed **review-bot** and **get-fellows-action**, using People parachain.  
Code part done by @Bullrich, I helped finishing it while he was on a sick leave

https://github.com/paritytech/get-fellows-action/pull/30
https://github.com/paritytech/review-bot/pull/131

https://github.com/polkadot-fellows/runtimes/pull/409
https://github.com/paritytech/polkadot-sdk/pull/5177

**Comment by Bullrich** [comment]
Updated all CI dependencies
- https://github.com/polkadot-fellows/runtimes/pull/400

**Comment by mordamax** [comment]
No updates this week, still waiting Basti & Tugy to spawn a runner. PR is ready

**Comment by Bullrich** [comment]
- paritytech/auto-merge-bot#29
  - paritytech/auto-merge-bot#30
  - https://github.com/polkadot-fellows/runtimes/pull/429

**Comment by mordamax** [comment]
This one was merged, 
- https://github.com/paritytech/product-engineering/issues/41

so closing the epic
